In [5]:
import openreview
import pandas as pd
import datetime as date
import tqdm

In [19]:
df_submissions = pd.read_csv('./data/submissions/df_submissions.csv')
client = openreview.Client(baseurl='https://api.openreview.net')

In [22]:
#takes about 10 minutes
list_all_notes = [client.get_notes(forum =forum) for forum in tqdm.tqdm(df_submissions.forum.tolist())]

100%|███████████████████████████████████████| 2820/2820 [17:00<00:00,  2.76it/s]

In [23]:
list_all_notes = [item for sublist in list_all_notes for item in sublist]
list_all_notes = [note.__dict__ for note in list_all_notes]

In [48]:
df_all_notes = pd.DataFrame(list_all_notes)
df_all_notes = pd.concat([df_all_notes, df_all_notes.content.apply(pd.Series)],axis = 1)
df_all_notes = df_all_notes.drop(columns=['content'])

In [47]:
def find_rr(row):
    row = row['invitation']
    row = row.lower()
    if (row.find('official') != -1):
        return 1
    else:
        return 0
    
def find_type(row):
    row = row['invitation']
    out = (row.rsplit('/',2)[-2:][0] + "_"+row.rsplit('/',2)[-2:][1]).lower()
    return out
    
def find_meta_review(row):
    row = row['invitation']
    row = row.lower()
    if (row.find('meta') != -1):
        return 1
    else:
        return 0

    

def find_year(row):
    row = row['invitation']
    x = row.split('/')
    return x[1]
    
    
#df_all_notes.invitation.str.rsplit(pat='/', n = 2,expand=True)

tqdm.tqdm.pandas()
df_all_notes['rr_flag'] = df_all_notes.progress_apply(lambda x: find_rr(x),axis=1)
df_all_notes['meta_flag'] = df_all_notes.progress_apply(lambda x: find_meta_review(x),axis=1)
df_all_notes['year'] = df_all_notes.progress_apply(lambda x: find_year(x),axis=1)

100%|█████████████████████████████████| 35487/35487 [00:00<00:00, 139186.51it/s]
100%|█████████████████████████████████| 35487/35487 [00:00<00:00, 150768.43it/s]
100%|█████████████████████████████████| 35487/35487 [00:00<00:00, 153641.81it/s]

In [99]:
df_all_notes.to_csv('./data/submissions/df_all_notes.csv',index=False)

In [48]:
df_all_notes.apply(lambda x: find_type(x), axis =1)

0                   -_submission
1               official_comment
2                 public_comment
3                official_review
4               official_comment
                  ...
35482     paper1_official_review
35483    paper1_official_comment
35484      paper1_public_comment
35485     paper1_official_review
35486         -_blind_submission
Length: 35487, dtype: object

In [93]:
df_all_notes.columns

Index(['id', 'original', 'number', 'cdate', 'mdate', 'tcdate', 'tmdate',
       'ddate', 'forum', 'referent', 'invitation', 'replyto', 'readers',
       'nonreaders', 'signatures', 'writers', 'details', 'TL;DR', 'title',
       'abstract', 'pdf', 'keywords', 'authors', 'conflicts', 'authorids',
       'venue', 'venueid', '_bibtex', 'paperhash', 'comment', 'rating',
       'review', 'confidence', 'question', 'decision', 'author_emails', 'code',
       'data', 'metareview', 'recommendation', 'withdrawal confirmation',
       'rr_flag', 'meta_flag', 'year'],
      dtype='object')

In [96]:
test  =df_all_notes[df_all_notes['meta_flag'] == 1]

In [97]:
test[['year','review','comment','invitation']]

,year,review,comment,invitation
1,2017,NaN,I thank the authors for their response and exp...,ICLR.cc/2017/conference/-/paper214/official/co...
3,2017,This paper proposes a new architecture that do...,NaN,ICLR.cc/2017/conference/-/paper214/official/re...
4,2017,NaN,"Authors claim that the reviewers reflect ""narr...",ICLR.cc/2017/conference/-/paper214/official/co...
6,2017,NaN,- Number of parameters needed is dramatically ...,ICLR.cc/2017/conference/-/paper214/official/co...
8,2017,This paper proposes a design principle for com...,NaN,ICLR.cc/2017/conference/-/paper214/official/re...
...,...,...,...,...
35480,2019,NaN,Thank you for the thoughtful review.\n\n - We ...,ICLR.cc/2019/Conference/-/Paper1/Official_Comment
35481,2019,The paper proposes a method for learning embed...,NaN,ICLR.cc/2019/Conference/-/Paper1/Official_Review
35482,2019,This paper proposes a soft relaxation of the b...,NaN,ICLR.cc/2019/Conference/-/Paper1/Official_Review
35483,2019,NaN,"Hi, thanks for the comment! We actually do cit...",ICLR.cc/2019/Conference/-/Paper1/Official_Comment
35485,2019,Post-rebuttal revision: All my concerns were a...,NaN,ICLR.cc/2019/Conference/-/Paper1/Official_Review

In [7]:
df_all_notes = pd.read_csv('../data/submissions/df_all_notes.csv')

/var/folders/v9/8whxr3fd1mv_pwkjh0kn920m0000gn/T/ipykernel_97056/1467377078.py:1: DtypeWarning: Columns (23,25,26,33,34,35,38,39,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df_all_notes = pd.read_csv('../data/submissions/df_all_notes.csv')

In [9]:
df_all_notes[df_all_notes['invitation'].str.contains('official')]

,id,original,number,cdate,mdate,tcdate,tmdate,ddate,forum,referent,...,decision,author_emails,code,data,metareview,recommendation,withdrawal confirmation,rr_flag,meta_flag,year
1,SJkBY2yve,NaN,4,NaN,NaN,1484929335077,1484929335077,NaN,S1VaB4cex,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,2017
3,r1tPX1rVg,NaN,2,NaN,NaN,1482122080695,1482122080695,NaN,S1VaB4cex,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,2017
4,ryKsOZQvl,NaN,5,NaN,NaN,1485146273283,1485146273283,NaN,S1VaB4cex,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,2017
6,HJYdQPeme,NaN,2,NaN,NaN,1480778608772,1480778608779,NaN,S1VaB4cex,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,2017
8,rkUFJWfNl,NaN,1,NaN,NaN,1481932670179,1484928792294,NaN,S1VaB4cex,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7458,BJLW1aJ7e,NaN,1,NaN,NaN,1480736509588,1480736509592,NaN,B1kJ6H9ex,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,2017
7462,H1BxzUzVl,NaN,1,NaN,NaN,1481953773328,1481953773328,NaN,B1kJ6H9ex,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,2017
7463,Hk2oimlSe,NaN,3,NaN,NaN,1482861475737,1482861475737,NaN,B1kJ6H9ex,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,2017
7465,ByXsQisNe,NaN,3,NaN,NaN,1482564507220,1482564507220,NaN,B1akgy9xx,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,2017
7475,S1h7tgZEx,NaN,2,NaN,NaN,1481865507814,1481865507814,NaN,B1akgy9xx,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,2017

In [49]:
#df_all_official_rebuttals = df_all_notes[(df_all_notes['rr_flag'] == 1) & (df_all_notes['comment'].notna())]
df_all_official_reviews = df_all_notes[(df_all_notes['rr_flag'] == 1) & (df_all_notes['review'].notna())]

print(len(df_all_official_reviews),len(df_all_official_rebuttals))
#df_all_rr = pd.merge(df_all_official_reviews, df_all_official_rebuttals, how="left", left_on = 'id',right_on ='replyto')

8569 14309

In [34]:
df_all_rr

,id_x,original_x,number_x,cdate_x,mdate_x,tcdate_x,tmdate_x,ddate_x,forum_x,referent_x,...,decision_y,author_emails_y,code_y,data_y,metareview_y,recommendation_y,withdrawal confirmation_y,rr_flag_y,meta_flag_y,year_y
0,r1tPX1rVg,NaN,2,NaN,NaN,1482122080695,1482122080695,NaN,S1VaB4cex,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,rkUFJWfNl,NaN,1,NaN,NaN,1481932670179,1484928792294,NaN,S1VaB4cex,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HJoOt0F4g,NaN,3,NaN,NaN,1482447219171,1482447219171,NaN,S1VaB4cex,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,rJU1aJpXx,NaN,1,NaN,NaN,1481600222497,1481600222501,NaN,H1W1UN9gg,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BJasd5ZEe,NaN,2,NaN,NaN,1481906340945,1481906340945,NaN,H1W1UN9gg,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9638,SkxbehICn7,NaN,2,1.541463e+12,NaN,1541463016695,1541534370443,NaN,S1gUVjCqKm,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,2019.0
9639,Bkx8Oznq27,NaN,1,1.541223e+12,NaN,1541223021529,1541534370190,NaN,S1gUVjCqKm,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,2019.0
9640,rJglCnOshm,NaN,3,1.541275e+12,NaN,1541274824287,1541534371550,NaN,H1xSNiRcF7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,2019.0
9641,SylZ79N5hm,NaN,2,1.541192e+12,NaN,1541192216792,1541534371337,NaN,H1xSNiRcF7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,2019.0
9642,H1xPEJOVsm,NaN,1,1.539764e+12,NaN,1539764015088,1543562954695,NaN,H1xSNiRcF7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,2019.0

In [33]:
df_all_rr.to_csv('../data/submissions/df_rr_pairs.csv')

In [59]:
#making convokit dataset
df_convokit = df_all_notes[df_all_notes['rr_flag'] == 1]
df_convokit = df_convokit[['id','tcdate','comment','review','signatures','replyto','forum','year']]
df_convokit['text'] = df_all_notes['comment'].fillna('')  + df_all_notes['review'].fillna('') 
df_convokit = df_convokit.drop(columns = ['comment','review'])
df_convokit = df_convokit[df_convokit['text']!='']
df_convokit.to_csv('./data/submissions/df_convokit.csv', index = False)